import { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import ap_sidebars from "./anchorPlatform.sidebar";
import sdp_sidebars from "./disbursementPlatform.sidebar";

const sidebars: SidebarsConfig = {
  build: [
    "build/README",
    "build/building-with-ai",
    {
      type: "category",
      label: "Agentic Payments",
      collapsed: false,
      link: {
        type: "doc",
        id: "build/agentic-payments/README",
      },
      items: [
        {
          type: "category",
          label: "x402",
          collapsed: false,
          link: {
            type: "doc",
            id: "build/agentic-payments/x402/README",
          },
          items: [
            "build/agentic-payments/x402/quickstart-guide",
            "build/agentic-payments/x402/built-on-stellar",
          ],
        },
        {
          type: "category",
          label: "MPP",
          collapsed: false,
          link: {
            type: "doc",
            id: "build/agentic-payments/mpp/README",
          },
          items: [
            "build/agentic-payments/mpp/charge-guide",
            "build/agentic-payments/mpp/channel-guide",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Smart Contracts",
      key: "build-smart-contracts",
      link: {
        type: "doc",
        id: "build/smart-contracts/README",
      },
      items: [
        "build/smart-contracts/overview",
        {
          type: "autogenerated",
          dirName: "build/smart-contracts/getting-started",
        },
        {
          type: "category",
          label: "Example Contracts",
          link: {
            type: "doc",
            id: "build/smart-contracts/example-contracts/README",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "build/smart-contracts/example-contracts",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Build Applications",
      link: {
        type: "doc",
        id: "build/apps/README",
      },
      items: [
        "build/apps/overview",
        "build/apps/application-design-considerations",
        {
          type: "autogenerated",
          dirName: "build/apps/wallet",
        },
        {
          type: "autogenerated",
          dirName: "build/apps/example-application-tutorial",
        },
        "build/apps/swift-payment-app",
        {
          type: "autogenerated",
          dirName: "build/apps/ingest-sdk",
        },
        {
          type: "autogenerated",
          dirName: "build/apps/guestbook",
        },
        "build/apps/dapp-frontend",
      ],
    },
    {
      type: "category",
      label: "Privacy on Stellar",
      link: {
        type: "doc",
        id: "build/apps/privacy",
      },
      items: ["build/apps/zk"],
    },
    {
      type: "doc",
      id: "build/tutorials",
      label: "Tutorials",
    },
    {
      type: "category",
      label: "How-To Guides",
      link: {
        type: "doc",
        id: "build/guides/README",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "build/guides",
        },
      ],
    },
    {
      type: "category",
      label: "Security Best Practices",
      link: {
        type: "doc",
        id: "build/security-docs/README",
      },
      items: [
        "build/security-docs/securing-web-based-projects",
        {
          type: "autogenerated",
          dirName: "build/security-docs/threat-modeling",
        },
      ],
    },
  ],
  learn: [
    {
      type: "autogenerated",
      dirName: "learn",
    },
  ],
  tokens: [
    {
      type: "autogenerated",
      dirName: "tokens",
    },
  ],
  data: [
    {
      type: "autogenerated",
      dirName: "data",
    },
  ],
  tools: [
    {
      type: "autogenerated",
      dirName: "tools",
    },
    {
      type: "html",
      value: "<small>SDF Platforms</small>",
      defaultStyle: true,
      className: "networkMenuHtmlItem",
    },
    {
      type: "link",
      href: "/docs/platforms/anchor-platform",
      label: "Anchor Platform",
    },
    {
      type: "link",
      href: "/docs/platforms/stellar-disbursement-platform",
      label: "Stellar Disbursement Platform",
    },
  ],
  networks: [
    {
      type: "autogenerated",
      dirName: "networks",
    },
  ],
  validators: [
    {
      type: "autogenerated",
      dirName: "validators",
    },
  ],
  anchor_platform: ap_sidebars.anchor_platform,
  stellar_disbursement_platform: sdp_sidebars.stellar_disbursement_platform,
};

export default sidebars;
